version: '3.1'

services:
  db:
    image: mariadb:10.6.4
    ports:
      - 3306:3306
    expose:
      - 3306
    volumes:
      - ./database/conf.d:/etc/mysql/conf.d
      - ./database/data:/var/lib/mysql
      - ./database/initdb.d:/docker-entrypoint-initdb.d
    env_file: .env
    environment:
      TZ: Asia/Seoul
    networks:
      - default
    restart: always

  app:
    image: crud-nodejs
    build: .
    working_dir: /usr/src/app
    depends_on:
      - db
    ports:
      - 80:8080
    command: bash -c "npm install && npm start"
    networks:
      - default
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules

networks:
  default: